/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-26 02:29:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import domain.qna.dao.QnaDao;
import java.util.HashMap;
import java.util.Map;
import com.google.gson.Gson;
import utils.Util;
import utils.Pagination;

public final class myPage_002dnavi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("utils.Util");
    _jspx_imports_classes.add("utils.Pagination");
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("domain.qna.dao.QnaDao");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	int USERNO = (Integer) session.getAttribute("USERNO");
	Map<String, Object> map = new HashMap<>();
	String section = request.getParameter("section");
	int pageNo = Util.toInt(request.getParameter("page"));
	
	if ("purchase".equals(section)) {
		domain.purchase.dao.BoardDao boardDao = new domain.purchase.dao.BoardDao();
		int purchaseTotalRows = boardDao.getTotalRowsByUserNo(USERNO);
		Pagination purchasePagination = new Pagination(pageNo, purchaseTotalRows, 5, 5);
		map.put("begin", purchasePagination.getBegin());
		map.put("beginPage", purchasePagination.getBeginPage());
		map.put("end", purchasePagination.getEnd());
		map.put("endPage", purchasePagination.getEndPage());
		map.put("next", purchasePagination.getNext());
		map.put("prev", purchasePagination.getPrev());
		map.put("totalRows", purchasePagination.getTotalRows());
		map.put("totalPages", purchasePagination.getTotalPages());
		map.put("isFirst", purchasePagination.isFirst());
		map.put("isLast", purchasePagination.isLast());
	}
	else if ("sell".equals(section)) {
		domain.sell.dao.BoardDao boardDao = new domain.sell.dao.BoardDao();
		int sellTotalRows = boardDao.getTotalRowsByUserNo(USERNO);
		Pagination sellPagination = new Pagination(pageNo, sellTotalRows, 5, 5);
		map.put("begin", sellPagination.getBegin());
		map.put("beginPage", sellPagination.getBeginPage());
		map.put("end", sellPagination.getEnd());
		map.put("endPage", sellPagination.getEndPage());
		map.put("next", sellPagination.getNext());
		map.put("prev", sellPagination.getPrev());
		map.put("totalRows", sellPagination.getTotalRows());
		map.put("totalPages", sellPagination.getTotalPages());
		map.put("isFirst", sellPagination.isFirst());
		map.put("isLast", sellPagination.isLast());
	}
	else if ("qna".equals(section)) {
		QnaDao qnaDao = new QnaDao();
		int qnaTotalRows = qnaDao.getTotalQnaRowsByUserNo(USERNO);
		Pagination qnaPagination = new Pagination(pageNo, qnaTotalRows, 5, 5);
		map.put("begin", qnaPagination.getBegin());
		map.put("beginPage", qnaPagination.getBeginPage());
		map.put("end", qnaPagination.getEnd());
		map.put("endPage", qnaPagination.getEndPage());
		map.put("next", qnaPagination.getNext());
		map.put("prev", qnaPagination.getPrev());
		map.put("totalRows", qnaPagination.getTotalRows());
		map.put("totalPages", qnaPagination.getTotalPages());
		map.put("isFirst", qnaPagination.isFirst());
		map.put("isLast", qnaPagination.isLast());
	}
	else if ("report".equals(section)) {
		QnaDao reportDao = new QnaDao();
		int reportTotalRows = reportDao.getTotalReportRowsByUserNo(USERNO);
		Pagination reportPagination = new Pagination(pageNo, reportTotalRows, 5, 5);
		map.put("begin", reportPagination.getBegin());
		map.put("beginPage", reportPagination.getBeginPage());
		map.put("end", reportPagination.getEnd());
		map.put("endPage", reportPagination.getEndPage());
		map.put("next", reportPagination.getNext());
		map.put("prev", reportPagination.getPrev());
		map.put("totalRows", reportPagination.getTotalRows());
		map.put("totalPages", reportPagination.getTotalPages());
		map.put("isFirst", reportPagination.isFirst());
		map.put("isLast", reportPagination.isLast());
	} 
	
	Gson gson = new Gson();
	String jsonText = gson.toJson(map);
	out.write(jsonText);

    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
